language: node_js

cache: yarn

node_js:
  - 'stable'
  - '12'
  - '14'

sudo: false

script:
  - yarn test

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true
